"""Client for sending mail via the Microsoft Graph API."""

import asyncio
import base64
import mimetypes
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import httpx

from app.config import GraphConfig
from app.format_size import format_size

_TOKEN_URL_TEMPLATE = "https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token"
_SEND_MAIL_URL_TEMPLATE = "https://graph.microsoft.com/v1.0/users/{sender_address}/sendMail"
_REQUEST_TIMEOUT_SECONDS = 30.0

#: Graph throttles aggressively under load (HTTP 429) -- retried this many
#: times (honoring the `Retry-After` header) before giving up.
_MAX_RETRIES = 3
#: Fallback wait if a 429 response has no (or an unparseable) `Retry-After`.
_DEFAULT_RETRY_AFTER_SECONDS = 5.0

#: Graph accepts an inline (non-upload-session) attachment up to this size,
#: enforced below. Real invoice PDFs generated by this app are ~55 KB, far
#: below it -- see `app.pdf.person_bill_pdf` -- but a broadcast email's
#: attachment (see `app.emailing.bulk_send.send_broadcast_email`) is
#: administrator-chosen and could be larger, hence the check; the simpler
#: upload-session flow for even bigger files was deliberately not built.
#: Microsoft's request-size ceiling for `sendMail`. Exceeding it is a 413,
#: no matter how the bytes are distributed across attachments.
MAX_REQUEST_BYTES = 4 * 1024 * 1024

#: Room left for everything that is not attachment content: subject, body,
#: recipient, and the JSON field names around it.
_ENVELOPE_ALLOWANCE_BYTES = 256 * 1024

#: How many raw attachment bytes one message may carry. Derived, not
#: guessed: attachments travel base64-encoded (see `send_email`), which
#: inflates them by 4/3, so the old flat "3 MB" produced a request of
#: exactly 4.00 MB at the boundary -- over the ceiling before the subject
#: was even added. Measured: 3 MiB raw -> 4.00 MB request, rejected.
MAX_INLINE_ATTACHMENT_BYTES = ((MAX_REQUEST_BYTES - _ENVELOPE_ALLOWANCE_BYTES) * 3) // 4


@dataclass(frozen=True)
class Attachment:
    """One file to attach to an outgoing email."""

    path: Path
    filename: str


class GraphAuthError(Exception):
    """Raised when Microsoft rejects the request due to invalid/expired credentials or insufficient..."""


class GraphApiError(Exception):
    """Raised for any other failure talking to the Graph API (network error, non-2xx status after..."""


async def get_access_token(config: GraphConfig) -> str:
    """Acquire an OAuth2 access token via the client-credentials flow."""
    url = _TOKEN_URL_TEMPLATE.format(tenant_id=config.tenant_id)
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                url,
                data={
                    "client_id": config.client_id,
                    "client_secret": config.client_secret,
                    "scope": "https://graph.microsoft.com/.default",
                    "grant_type": "client_credentials",
                },
                timeout=_REQUEST_TIMEOUT_SECONDS,
            )
    except httpx.RequestError as exc:
        raise GraphApiError(f"Anmeldedienst (Entra ID) nicht erreichbar: {exc}") from exc

    if response.status_code != 200:
        try:
            description = response.json().get("error_description", response.text[:300])
        except ValueError:
            description = response.text[:300]
        raise GraphAuthError(
            "Anmeldung bei Microsoft fehlgeschlagen -- Tenant-ID/Client-ID/"
            f"Client-Secret in config.local.json prüfen. Details: {description}"
        )

    try:
        return response.json()["access_token"]
    except (ValueError, KeyError, TypeError) as exc:
        raise GraphApiError(f"Anmeldedienst lieferte keinen gültigen Token: {exc}") from exc


async def send_email(
    config: GraphConfig,
    access_token: str,
    *,
    to_addresses: Sequence[str],
    to_name: str,
    subject: str,
    body: str,
    attachments: Sequence[Attachment] = (),
) -> None:
    """Send one plain-text email to exactly one contract party."""
    if not to_addresses:
        # A GraphApiError rather than a ValueError on purpose: callers
        # (app.emailing.bulk_send) catch Graph* per recipient, so this
        # becomes a clean per-party skip instead of aborting the batch.
        raise GraphApiError(f"Keine E-Mail-Adresse für {to_name or 'diesen Empfänger'} hinterlegt.")
    message: dict = {
        "subject": subject,
        "body": {"contentType": "Text", "content": body},
        "toRecipients": [{"emailAddress": {"address": address, "name": to_name}} for address in to_addresses],
    }
    if attachments:
        payload_attachments = []
        total_bytes = 0
        for attachment in attachments:
            try:
                content_bytes = attachment.path.read_bytes()
            except OSError as exc:
                # Deliberately a GraphApiError, not a raw OSError: callers
                # (app.emailing.bulk_send) only catch Graph* exceptions per
                # recipient, so a PDF deleted/moved after being generated
                # (see app.pdf.export_service) becomes a clean per-person
                # skip instead of crashing the whole batch send.
                raise GraphApiError(f"Anhang {attachment.path} konnte nicht gelesen werden: {exc}") from exc
            total_bytes += len(content_bytes)
            content_type = mimetypes.guess_type(attachment.filename or str(attachment.path))[0]
            payload_attachments.append(
                {
                    "@odata.type": "#microsoft.graph.fileAttachment",
                    "name": attachment.filename,
                    "contentType": content_type or "application/octet-stream",
                    "contentBytes": base64.b64encode(content_bytes).decode("ascii"),
                }
            )
        # Checked over the total: Microsoft's limit is on the message, so
        # three 2 MB files fail even though each one alone would pass.
        if total_bytes > MAX_INLINE_ATTACHMENT_BYTES:
            names = ", ".join(a.filename for a in attachments)
            raise GraphApiError(
                f"Anhänge ({names}) sind zusammen mit "
                f"{format_size(total_bytes)} zu gross -- erlaubt sind hier "
                f"insgesamt {format_size(MAX_INLINE_ATTACHMENT_BYTES)} "
                "(Microsoft begrenzt die ganze Anfrage auf 4 MB, und Anhänge "
                "werden base64-codiert um ein Drittel grösser)."
            )
        message["attachments"] = payload_attachments

    # Named once for the error messages below: a couple's message carries
    # two addresses, and a failure has to say which party it was about.
    recipient_label = ", ".join(to_addresses)

    url = _SEND_MAIL_URL_TEMPLATE.format(sender_address=config.sender_address)
    headers = {"Authorization": f"Bearer {access_token}"}
    payload = {"message": message, "saveToSentItems": "true"}

    for attempt in range(_MAX_RETRIES + 1):
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    url, json=payload, headers=headers, timeout=_REQUEST_TIMEOUT_SECONDS
                )
        except httpx.RequestError as exc:
            raise GraphApiError(f"Microsoft Graph nicht erreichbar: {exc}") from exc

        if response.status_code == 202:
            return
        if response.status_code in (401, 403):
            raise GraphAuthError(
                f"Microsoft Graph hat den Versand an {recipient_label} verweigert "
                f"(Status {response.status_code}) -- Zugangsdaten oder Postfach-"
                f"Berechtigung für {config.sender_address} prüfen."
            )
        if response.status_code == 429 and attempt < _MAX_RETRIES:
            retry_after = _parse_retry_after(response.headers.get("Retry-After"))
            await asyncio.sleep(retry_after)
            continue

        raise GraphApiError(
            f"Microsoft Graph antwortete mit Status {response.status_code} "
            f"beim Versand an {recipient_label}: {response.text[:200]}"
        )


def _parse_retry_after(raw_value: Optional[str]) -> float:
    """Parse a `Retry-After` header value into a wait time in seconds."""
    if raw_value is None:
        return _DEFAULT_RETRY_AFTER_SECONDS
    try:
        return max(float(raw_value), 0.0)
    except ValueError:
        return _DEFAULT_RETRY_AFTER_SECONDS
