"""Client for sending mail via the Microsoft Graph API.

Fixed API contract:

    POST https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token
    POST https://graph.microsoft.com/v1.0/users/{sender_address}/sendMail

Authenticated via OAuth2 client-credentials (an Entra ID app registration
with the `Mail.Send` *application* permission, admin-consented) -- plain
SMTP with a username/password is not a viable option here since Microsoft
has retired Basic Auth for SMTP AUTH across Exchange Online tenants.

Deliberately `async` (using `httpx.AsyncClient` rather than the sync
`httpx.get`/`.post` used by `app.importers.cloudflare_client`): sending to
many recipients means one `sendMail` call per person (see module
docstring of `app.emailing`), and `await`ing each one lets NiceGUI's event
loop repaint a progress indicator between sends instead of freezing the
UI for the whole batch.
"""

import asyncio
import base64
import mimetypes
from pathlib import Path
from typing import Optional

import httpx

from app.config import GraphConfig

_TOKEN_URL_TEMPLATE = "https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token"
_SEND_MAIL_URL_TEMPLATE = "https://graph.microsoft.com/v1.0/users/{sender_address}/sendMail"
_REQUEST_TIMEOUT_SECONDS = 30.0

#: Graph throttles aggressively under load (HTTP 429) -- retried this many
#: times (honoring the `Retry-After` header) before giving up.
_MAX_RETRIES = 3
#: Fallback wait if a 429 response has no (or an unparseable) `Retry-After`.
_DEFAULT_RETRY_AFTER_SECONDS = 5.0

#: Graph accepts an inline (non-upload-session) attachment up to this size,
#: enforced below. Real invoice PDFs generated by this app are ~55 KB, far
#: below it -- see `app.pdf.person_bill_pdf` -- but a broadcast email's
#: attachment (see `app.emailing.bulk_send.send_broadcast_email`) is
#: administrator-chosen and could be larger, hence the check; the simpler
#: upload-session flow for even bigger files was deliberately not built.
MAX_INLINE_ATTACHMENT_BYTES = 3 * 1024 * 1024


class GraphAuthError(Exception):
    """Raised when Microsoft rejects the request due to invalid/expired
    credentials or insufficient permission (token request failure, or a
    401/403 from the Graph API itself)."""


class GraphApiError(Exception):
    """Raised for any other failure talking to the Graph API (network
    error, non-2xx status after retries, or an unparseable response)."""


async def get_access_token(config: GraphConfig) -> str:
    """Acquire an OAuth2 access token via the client-credentials flow.

    Args:
        config: Graph API credentials (see `app.config.get_graph_config`).

    Returns:
        A bearer token valid for the standard Entra ID token lifetime
        (typically ~60-90 minutes) -- long enough to reuse for an entire
        bulk-send batch without reacquiring it per recipient.

    Raises:
        GraphAuthError: If the tenant/client id or secret are invalid.
        GraphApiError: For any other network or HTTP failure, or an
            unparseable response body.
    """
    url = _TOKEN_URL_TEMPLATE.format(tenant_id=config.tenant_id)
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                url,
                data={
                    "client_id": config.client_id,
                    "client_secret": config.client_secret,
                    "scope": "https://graph.microsoft.com/.default",
                    "grant_type": "client_credentials",
                },
                timeout=_REQUEST_TIMEOUT_SECONDS,
            )
    except httpx.RequestError as exc:
        raise GraphApiError(f"Anmeldedienst (Entra ID) nicht erreichbar: {exc}") from exc

    if response.status_code != 200:
        try:
            description = response.json().get("error_description", response.text[:300])
        except ValueError:
            description = response.text[:300]
        raise GraphAuthError(
            "Anmeldung bei Microsoft fehlgeschlagen -- Tenant-ID/Client-ID/"
            f"Client-Secret in config.local.json prüfen. Details: {description}"
        )

    try:
        return response.json()["access_token"]
    except (ValueError, KeyError, TypeError) as exc:
        raise GraphApiError(f"Anmeldedienst lieferte keinen gültigen Token: {exc}") from exc


async def send_email(
    config: GraphConfig,
    access_token: str,
    *,
    to_address: str,
    to_name: str,
    subject: str,
    body: str,
    attachment_path: Optional[Path] = None,
    attachment_filename: Optional[str] = None,
) -> None:
    """Send one plain-text email to exactly one recipient.

    Deliberately always exactly one entry in `toRecipients` and never any
    CC/BCC -- that is the whole privacy mechanism for bulk sends (see
    `app.emailing` module docstring): call this once per recipient rather
    than once with many addresses.

    Args:
        config: Graph API credentials.
        access_token: Bearer token from `get_access_token`.
        to_address: Recipient's email address.
        to_name: Recipient's display name.
        subject: Email subject.
        body: Plain-text email body.
        attachment_path: Optional file to attach (any type -- an invoice
            PDF, see `app.emailing.bulk_send._send_one_invoice_email`, or
            an administrator-chosen file for a broadcast email, see
            `app.emailing.bulk_send.send_broadcast_email`). Its content
            type is guessed from `attachment_filename` via `mimetypes`,
            falling back to `application/octet-stream`.
        attachment_filename: Filename shown for the attachment (required
            if `attachment_path` is given).

    Returns:
        None.

    Raises:
        GraphAuthError: If the access token is invalid/expired, or the
            app registration lacks permission to send as this mailbox.
        GraphApiError: For any other failure (including exhausting the
            429-retry budget, or an attachment over
            `MAX_INLINE_ATTACHMENT_BYTES`).
    """
    message: dict = {
        "subject": subject,
        "body": {"contentType": "Text", "content": body},
        "toRecipients": [{"emailAddress": {"address": to_address, "name": to_name}}],
    }
    if attachment_path is not None:
        try:
            content_bytes = attachment_path.read_bytes()
        except OSError as exc:
            # Deliberately a GraphApiError, not a raw OSError: callers
            # (app.emailing.bulk_send) only catch Graph* exceptions per
            # recipient, so a PDF deleted/moved after being generated
            # (see app.pdf.export_service) becomes a clean per-person
            # skip instead of crashing the whole batch send.
            raise GraphApiError(f"Anhang {attachment_path} konnte nicht gelesen werden: {exc}") from exc
        if len(content_bytes) > MAX_INLINE_ATTACHMENT_BYTES:
            raise GraphApiError(
                f"Anhang {attachment_filename} ist mit "
                f"{len(content_bytes) / 1024 / 1024:.1f} MB zu gross -- Microsoft "
                f"Graph erlaubt hier maximal {MAX_INLINE_ATTACHMENT_BYTES // 1024 // 1024} MB."
            )
        content_type = mimetypes.guess_type(attachment_filename or str(attachment_path))[0]
        message["attachments"] = [
            {
                "@odata.type": "#microsoft.graph.fileAttachment",
                "name": attachment_filename,
                "contentType": content_type or "application/octet-stream",
                "contentBytes": base64.b64encode(content_bytes).decode("ascii"),
            }
        ]

    url = _SEND_MAIL_URL_TEMPLATE.format(sender_address=config.sender_address)
    headers = {"Authorization": f"Bearer {access_token}"}
    payload = {"message": message, "saveToSentItems": "true"}

    for attempt in range(_MAX_RETRIES + 1):
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    url, json=payload, headers=headers, timeout=_REQUEST_TIMEOUT_SECONDS
                )
        except httpx.RequestError as exc:
            raise GraphApiError(f"Microsoft Graph nicht erreichbar: {exc}") from exc

        if response.status_code == 202:
            return
        if response.status_code in (401, 403):
            raise GraphAuthError(
                f"Microsoft Graph hat den Versand an {to_address} verweigert "
                f"(Status {response.status_code}) -- Zugangsdaten oder Postfach-"
                f"Berechtigung für {config.sender_address} prüfen."
            )
        if response.status_code == 429 and attempt < _MAX_RETRIES:
            retry_after = _parse_retry_after(response.headers.get("Retry-After"))
            await asyncio.sleep(retry_after)
            continue

        raise GraphApiError(
            f"Microsoft Graph antwortete mit Status {response.status_code} "
            f"beim Versand an {to_address}: {response.text[:200]}"
        )


def _parse_retry_after(raw_value: Optional[str]) -> float:
    """Parse a `Retry-After` header value into a wait time in seconds.

    Args:
        raw_value: The header's raw value (seconds as an integer string
            per RFC 9110 -- Graph does not use the HTTP-date form), or
            `None` if the header was absent.

    Returns:
        The parsed number of seconds, or `_DEFAULT_RETRY_AFTER_SECONDS` if
        `raw_value` is missing or not a plain number.
    """
    if raw_value is None:
        return _DEFAULT_RETRY_AFTER_SECONDS
    try:
        return max(float(raw_value), 0.0)
    except ValueError:
        return _DEFAULT_RETRY_AFTER_SECONDS
