"""Time-bounded assignments of meters to participants (Zuordnungs-Historie).

A meter is physically fixed to a building, but the participant living or
producing there can change over time (e.g. a tenant moving out mid-quarter).
Each row in `meter_assignments` represents one such period; `valid_to =
NULL` means "still valid / open-ended".
"""

import sqlite3
from dataclasses import dataclass
from datetime import date, datetime, timezone
from typing import Optional


@dataclass
class MeterAssignment:
    """One period during which a meter belonged to a given participant.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        meter_id: Foreign key to the assigned meter.
        participant_id: Foreign key to the participant.
        valid_from: First calendar day (inclusive) this assignment applies.
        valid_to: Last calendar day (inclusive) this assignment applies, or
            `None` if the assignment is open-ended (still current).
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    meter_id: int
    participant_id: int
    valid_from: date
    valid_to: Optional[date]
    created_at: str

    @staticmethod
    def from_row(row: sqlite3.Row) -> "MeterAssignment":
        """Build a `MeterAssignment` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `meter_assignments` table.

        Returns:
            The corresponding `MeterAssignment` dataclass instance.
        """
        return MeterAssignment(
            id=row["id"],
            meter_id=row["meter_id"],
            participant_id=row["participant_id"],
            valid_from=date.fromisoformat(row["valid_from"]),
            valid_to=date.fromisoformat(row["valid_to"]) if row["valid_to"] else None,
            created_at=row["created_at"],
        )

    def covers(self, moment: datetime) -> bool:
        """Check whether this assignment is active at a given point in time.

        Args:
            moment: Timestamp to test (only its calendar date is compared).

        Returns:
            `True` if `valid_from <= moment.date() <= valid_to` (or
            `valid_to` is `None`, meaning open-ended).
        """
        moment_date = moment.date()
        if moment_date < self.valid_from:
            return False
        if self.valid_to is not None and moment_date > self.valid_to:
            return False
        return True


def list_for_meter(
    connection: sqlite3.Connection, meter_id: int
) -> list[MeterAssignment]:
    """List all assignments of a meter, most recent `valid_from` first.

    Args:
        connection: Open SQLite connection.
        meter_id: Primary key of the meter.

    Returns:
        All assignments for the meter, ordered by `valid_from` descending.
    """
    rows = connection.execute(
        "SELECT * FROM meter_assignments WHERE meter_id = ? ORDER BY valid_from DESC",
        (meter_id,),
    ).fetchall()
    return [MeterAssignment.from_row(row) for row in rows]


def list_all(connection: sqlite3.Connection) -> list[MeterAssignment]:
    """List every assignment in the database.

    Args:
        connection: Open SQLite connection.

    Returns:
        All assignments, ordered by meter id and `valid_from`.
    """
    rows = connection.execute(
        "SELECT * FROM meter_assignments ORDER BY meter_id, valid_from"
    ).fetchall()
    return [MeterAssignment.from_row(row) for row in rows]


def create(connection: sqlite3.Connection, assignment: MeterAssignment) -> int:
    """Insert a new meter assignment.

    Args:
        connection: Open SQLite connection.
        assignment: Assignment data to insert; `id` and `created_at` are
            ignored and generated by this function.

    Returns:
        The primary key of the newly created assignment.
    """
    cursor = connection.execute(
        """
        INSERT INTO meter_assignments
            (meter_id, participant_id, valid_from, valid_to, created_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            assignment.meter_id,
            assignment.participant_id,
            assignment.valid_from.isoformat(),
            assignment.valid_to.isoformat() if assignment.valid_to else None,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, assignment: MeterAssignment) -> None:
    """Update an existing assignment's validity period or participant.

    Args:
        connection: Open SQLite connection.
        assignment: Assignment with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `assignment.id` is `None`.
    """
    if assignment.id is None:
        raise ValueError("Cannot update an assignment without an id.")
    connection.execute(
        """
        UPDATE meter_assignments SET
            meter_id = ?, participant_id = ?, valid_from = ?, valid_to = ?
        WHERE id = ?
        """,
        (
            assignment.meter_id,
            assignment.participant_id,
            assignment.valid_from.isoformat(),
            assignment.valid_to.isoformat() if assignment.valid_to else None,
            assignment.id,
        ),
    )
    connection.commit()


def delete(connection: sqlite3.Connection, assignment_id: int) -> None:
    """Delete a meter assignment.

    Args:
        connection: Open SQLite connection.
        assignment_id: Primary key of the assignment to delete.

    Returns:
        None.
    """
    connection.execute(
        "DELETE FROM meter_assignments WHERE id = ?", (assignment_id,)
    )
    connection.commit()


@dataclass
class AssignmentWarning:
    """A detected problem in a meter's assignment history.

    Attributes:
        meter_id: Meter the warning refers to.
        kind: Either "overlap" (two assignments cover the same day) or
            "gap" (a day between assignments belongs to nobody).
        message: Human-readable (German) description for display in the UI.
    """

    meter_id: int
    kind: str
    message: str


def find_warnings(
    connection: sqlite3.Connection, meter_id: int
) -> list[AssignmentWarning]:
    """Detect overlapping or gapped assignment periods for one meter.

    Assignments are checked pairwise after sorting by `valid_from`: any two
    consecutive periods that overlap, or that leave a day uncovered between
    them, produce a warning. Open-ended assignments (`valid_to is None`)
    are only allowed to be the last one; an earlier open-ended assignment is
    reported as an overlap with everything that follows it.

    Args:
        connection: Open SQLite connection.
        meter_id: Primary key of the meter to check.

    Returns:
        A list of `AssignmentWarning`, empty if the history is consistent.
    """
    assignments = sorted(
        list_for_meter(connection, meter_id), key=lambda a: a.valid_from
    )
    warnings: list[AssignmentWarning] = []

    for earlier, later in zip(assignments, assignments[1:]):
        earlier_end = earlier.valid_to
        if earlier_end is None or earlier_end >= later.valid_from:
            warnings.append(
                AssignmentWarning(
                    meter_id=meter_id,
                    kind="overlap",
                    message=(
                        f"Überlappende Zuordnungen bei Zähler {meter_id}: "
                        f"{earlier.valid_from} - "
                        f"{earlier_end or 'offen'} und ab {later.valid_from}."
                    ),
                )
            )
        else:
            from datetime import timedelta

            if earlier_end + timedelta(days=1) < later.valid_from:
                warnings.append(
                    AssignmentWarning(
                        meter_id=meter_id,
                        kind="gap",
                        message=(
                            f"Lücke in Zuordnungen bei Zähler {meter_id}: "
                            f"{earlier_end + timedelta(days=1)} bis "
                            f"{later.valid_from - timedelta(days=1)} ist "
                            "niemandem zugeordnet."
                        ),
                    )
                )

    return warnings
