"""LEG (Lokale Elektrizitätsgemeinschaft): the administrative and billing
entity a Standort belongs to. By default one LEG corresponds to exactly
one physical Trafokreis (transformer circuit) -- its `name` typically
starts out as the Trafokreis's own designation -- but a LEG can
deliberately span Standorte on more than one Trafokreis if their owners
agree to form a joint LEG (at a correspondingly different internal
discount/tariff arrangement negotiated with the grid operator, outside
this app's concern). Never attached to a Person or Messpunkt directly --
see `app.models.standort`.

Billing runs (see `app.domain.billing`) are scoped to exactly one LEG at a
time: local sharing only ever happens between Messpunkte whose Standorte
belong to the same LEG (see `app.domain.distribution`), and each LEG gets
its own name on its invoices' letterhead -- everything else (address,
QR-IBAN, energy price, admin fees) is shared across all LEGs, see
`app.models.settings`.
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Leg:
    """One LEG (billing entity), by default matching one Trafokreis.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        name: The LEG's name -- the official BKW Trafokreis designation if
            it matches one physical Trafokreis 1:1, a self-chosen name
            otherwise (e.g. a joint LEG spanning several Trafokreise).
            Must be unique, and is what appears on this LEG's invoices.
        gemeinde: Municipality the LEG is located in.
        bemerkung: Free-text notes (optional).
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    name: str
    gemeinde: str
    bemerkung: str
    created_at: str

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Leg":
        """Build a `Leg` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `leg` table.

        Returns:
            The corresponding `Leg` dataclass instance.
        """
        return Leg(
            id=row["id"],
            name=row["name"],
            gemeinde=row["gemeinde"],
            bemerkung=row["bemerkung"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Leg]:
    """List all LEGs, ordered by municipality then name.

    Args:
        connection: Open SQLite connection.

    Returns:
        All LEGs, sorted by `gemeinde` then `name`.
    """
    rows = connection.execute("SELECT * FROM leg ORDER BY gemeinde, name").fetchall()
    return [Leg.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, leg_id: int) -> Optional[Leg]:
    """Fetch a single LEG by id.

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG.

    Returns:
        The matching `Leg`, or `None` if no such id exists.
    """
    row = connection.execute("SELECT * FROM leg WHERE id = ?", (leg_id,)).fetchone()
    return Leg.from_row(row) if row else None


def get_by_name(connection: sqlite3.Connection, name: str) -> Optional[Leg]:
    """Fetch a single LEG by its exact name.

    Args:
        connection: Open SQLite connection.
        name: LEG name to look up.

    Returns:
        The matching `Leg`, or `None` if no such name exists.
    """
    row = connection.execute("SELECT * FROM leg WHERE name = ?", (name,)).fetchone()
    return Leg.from_row(row) if row else None


def create(connection: sqlite3.Connection, leg: Leg) -> int:
    """Insert a new LEG.

    Args:
        connection: Open SQLite connection.
        leg: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created LEG.

    Raises:
        sqlite3.IntegrityError: If `leg.name` is already in use.
    """
    cursor = connection.execute(
        """
        INSERT INTO leg (name, gemeinde, bemerkung, created_at)
        VALUES (?, ?, ?, ?)
        """,
        (
            leg.name,
            leg.gemeinde,
            leg.bemerkung,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, leg: Leg) -> None:
    """Update an existing LEG's data.

    Args:
        connection: Open SQLite connection.
        leg: LEG with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `leg.id` is `None`.
        sqlite3.IntegrityError: If `leg.name` is already used by a
            different LEG.
    """
    if leg.id is None:
        raise ValueError("Cannot update a LEG without an id.")
    connection.execute(
        """
        UPDATE leg SET
            name = ?, gemeinde = ?, bemerkung = ?
        WHERE id = ?
        """,
        (leg.name, leg.gemeinde, leg.bemerkung, leg.id),
    )
    connection.commit()


def count_standorte(connection: sqlite3.Connection, leg_id: int) -> int:
    """Count the Standorte currently assigned to a LEG.

    Used to guard deletion: a LEG with assigned Standorte must not be
    deleted (see `delete`).

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG.

    Returns:
        The number of `standort` rows referencing this LEG.
    """
    row = connection.execute(
        "SELECT COUNT(*) AS n FROM standort WHERE leg_id = ?", (leg_id,)
    ).fetchone()
    return row["n"]


class LegInUseError(Exception):
    """Raised when deleting a LEG that still has assigned Standorte."""


def delete(connection: sqlite3.Connection, leg_id: int) -> None:
    """Delete a LEG, but only if no Standort is assigned to it.

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG to delete.

    Returns:
        None.

    Raises:
        LegInUseError: If one or more Standorte still reference this LEG.
    """
    if count_standorte(connection, leg_id) > 0:
        raise LegInUseError(
            "LEG kann nicht gelöscht werden: es sind noch Standorte zugeordnet."
        )
    connection.execute("DELETE FROM leg WHERE id = ?", (leg_id,))
    connection.commit()
