"""LEG (Lokale Elektrizitätsgemeinschaft): the administrative and billing
group an individual Messpunkt opts into. Attached to the Messpunkt itself,
never to a Standort or Person directly -- two Messpunkte at the very same
Standort (and thus the same Trafokreis, see `app.models.trafokreis`) can
belong to different LEGs, and one LEG can combine Messpunkte spread across
several Trafokreise if their owners agree to bill jointly (at a
correspondingly lower BKW discount for the cross-Trafokreis share, which
this app never computes but can flag -- see `app.domain.leg_composition`).

Billing runs (see `app.domain.billing`) are scoped to exactly one LEG at a
time: local sharing only ever happens between Messpunkte belonging to the
same LEG (see `app.domain.distribution`), and each LEG gets its own name on
its invoices' letterhead -- everything else (address, QR-IBAN, energy
price, admin fees) is shared across all LEGs, see `app.models.settings`.
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Leg:
    """One LEG (billing entity), attached to individual Messpunkte.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        name: The LEG's name -- typically the Trafokreis designation it
            matches 1:1, a self-chosen name otherwise (e.g. a joint LEG
            spanning several Trafokreise). Must be unique, and is what
            appears on this LEG's invoices.
        bemerkung: Free-text notes (optional).
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    name: str
    bemerkung: str
    created_at: str

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Leg":
        """Build a `Leg` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `leg` table.

        Returns:
            The corresponding `Leg` dataclass instance.
        """
        return Leg(
            id=row["id"],
            name=row["name"],
            bemerkung=row["bemerkung"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Leg]:
    """List all LEGs, ordered by name.

    Args:
        connection: Open SQLite connection.

    Returns:
        All LEGs, sorted by `name`.
    """
    rows = connection.execute("SELECT * FROM leg ORDER BY name").fetchall()
    return [Leg.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, leg_id: int) -> Optional[Leg]:
    """Fetch a single LEG by id.

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG.

    Returns:
        The matching `Leg`, or `None` if no such id exists.
    """
    row = connection.execute("SELECT * FROM leg WHERE id = ?", (leg_id,)).fetchone()
    return Leg.from_row(row) if row else None


def get_by_name(connection: sqlite3.Connection, name: str) -> Optional[Leg]:
    """Fetch a single LEG by its exact name.

    Args:
        connection: Open SQLite connection.
        name: LEG name to look up.

    Returns:
        The matching `Leg`, or `None` if no such name exists.
    """
    row = connection.execute("SELECT * FROM leg WHERE name = ?", (name,)).fetchone()
    return Leg.from_row(row) if row else None


def create(connection: sqlite3.Connection, leg: Leg) -> int:
    """Insert a new LEG.

    Args:
        connection: Open SQLite connection.
        leg: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created LEG.

    Raises:
        sqlite3.IntegrityError: If `leg.name` is already in use.
    """
    cursor = connection.execute(
        """
        INSERT INTO leg (name, bemerkung, created_at)
        VALUES (?, ?, ?)
        """,
        (
            leg.name,
            leg.bemerkung,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, leg: Leg) -> None:
    """Update an existing LEG's data.

    Args:
        connection: Open SQLite connection.
        leg: LEG with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `leg.id` is `None`.
        sqlite3.IntegrityError: If `leg.name` is already used by a
            different LEG.
    """
    if leg.id is None:
        raise ValueError("Cannot update a LEG without an id.")
    connection.execute(
        """
        UPDATE leg SET
            name = ?, bemerkung = ?
        WHERE id = ?
        """,
        (leg.name, leg.bemerkung, leg.id),
    )
    connection.commit()


def count_messpunkte(connection: sqlite3.Connection, leg_id: int) -> int:
    """Count the Messpunkte currently assigned to a LEG.

    Used to guard deletion: a LEG with assigned Messpunkte must not be
    deleted (see `delete`).

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG.

    Returns:
        The number of `messpunkt` rows referencing this LEG.
    """
    row = connection.execute(
        "SELECT COUNT(*) AS n FROM messpunkt WHERE leg_id = ?", (leg_id,)
    ).fetchone()
    return row["n"]


class LegInUseError(Exception):
    """Raised when deleting a LEG that still has assigned Messpunkte."""


def delete(connection: sqlite3.Connection, leg_id: int) -> None:
    """Delete a LEG, but only if no Messpunkt is assigned to it.

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG to delete.

    Returns:
        None.

    Raises:
        LegInUseError: If one or more Messpunkte still reference this LEG.
    """
    if count_messpunkte(connection, leg_id) > 0:
        raise LegInUseError(
            "LEG kann nicht gelöscht werden: es sind noch Messpunkte zugeordnet."
        )
    connection.execute("DELETE FROM leg WHERE id = ?", (leg_id,))
    connection.commit()
