"""LEG (Lokale Elektrizitätsgemeinschaft): the administrative and billing
group an individual MeteringPoint opts into. Attached to the MeteringPoint itself,
never to a site or Person directly -- two metering points at the very same
site (and thus the same substation area, see `app.models.substation_area`) can
belong to different LEGs, and one LEG can combine metering points spread across
several substation areas if their owners agree to bill jointly (at a
correspondingly lower BKW discount for the cross-substation-area share, which
this app never computes but can flag -- see `app.domain.leg_composition`).

Billing runs (see `app.domain.billing`) are scoped to exactly one LEG at a
time: local sharing only ever happens between metering points belonging to the
same LEG (see `app.domain.distribution`), and each LEG gets its own name on
its invoices' letterhead -- everything else (address, QR-IBAN, energy
price, admin fees) is shared across all LEGs, see `app.models.settings`.
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

#: The BKW discount tier a LEG gets on the Netznutzung, by its stored
#: value. BKW grants 40% where the locally shared electricity needs no
#: transformation stage and 20% where it does, and calls the two "hohe"
#: and "niedrige Rabattstufe" on its own LEG pages. Entered by hand: the
#: tier follows from BKW's grid topology and is confirmed by BKW per
#: location, so the app must not guess it -- whether a LEG spans several
#: Trafokreise (see `app.domain.leg_composition`) correlates with it but
#: is a different statement.
DISCOUNT_LEVEL_HIGH = "high"
DISCOUNT_LEVEL_LOW = "low"
DISCOUNT_LEVEL_UNKNOWN = "unknown"

#: German labels for the three values, for selects and printouts.
DISCOUNT_LEVEL_OPTIONS = {
    DISCOUNT_LEVEL_UNKNOWN: "Noch nicht bekannt",
    DISCOUNT_LEVEL_HIGH: "Hohe Rabattstufe (40% Rabatt auf die Netznutzung)",
    DISCOUNT_LEVEL_LOW: "Niedrige Rabattstufe (20% Rabatt auf die Netznutzung)",
}

#: Short forms of the same, for the overview card and the printed table.
DISCOUNT_LEVEL_SHORT = {
    DISCOUNT_LEVEL_UNKNOWN: "Rabattstufe unbekannt",
    DISCOUNT_LEVEL_HIGH: "Hohe Rabattstufe (40%)",
    DISCOUNT_LEVEL_LOW: "Niedrige Rabattstufe (20%)",
}


@dataclass
class Leg:
    """One LEG (billing entity), attached to individual metering points.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        name: The LEG's name -- typically the substation area designation it
            matches 1:1, a self-chosen name otherwise (e.g. a joint LEG
            spanning several substation areas). Must be unique, and is what
            appears on this LEG's invoices.
        note: Free-text notes (optional).
        created_at: ISO-8601 creation timestamp.
        discount_level: Which BKW discount tier this LEG gets, one of
            `DISCOUNT_LEVEL_HIGH`/`_LOW`/`_UNKNOWN` -- see those constants.
    """

    id: Optional[int]
    name: str
    note: str
    created_at: str
    discount_level: str = DISCOUNT_LEVEL_UNKNOWN

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Leg":
        """Build a `Leg` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `leg` table.

        Returns:
            The corresponding `Leg` dataclass instance.
        """
        return Leg(
            id=row["id"],
            name=row["name"],
            note=row["note"],
            created_at=row["created_at"],
            discount_level=row["discount_level"],
        )


def list_all(connection: sqlite3.Connection) -> list[Leg]:
    """List all LEGs, ordered by name.

    Args:
        connection: Open SQLite connection.

    Returns:
        All LEGs, sorted by `name`.
    """
    rows = connection.execute("SELECT * FROM leg ORDER BY name").fetchall()
    return [Leg.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, leg_id: int) -> Optional[Leg]:
    """Fetch a single LEG by id.

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG.

    Returns:
        The matching `Leg`, or `None` if no such id exists.
    """
    row = connection.execute("SELECT * FROM leg WHERE id = ?", (leg_id,)).fetchone()
    return Leg.from_row(row) if row else None


def get_by_name(connection: sqlite3.Connection, name: str) -> Optional[Leg]:
    """Fetch a single LEG by its exact name.

    Args:
        connection: Open SQLite connection.
        name: LEG name to look up.

    Returns:
        The matching `Leg`, or `None` if no such name exists.
    """
    row = connection.execute("SELECT * FROM leg WHERE name = ?", (name,)).fetchone()
    return Leg.from_row(row) if row else None


def create(connection: sqlite3.Connection, leg: Leg) -> int:
    """Insert a new LEG.

    Args:
        connection: Open SQLite connection.
        leg: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created LEG.

    Raises:
        sqlite3.IntegrityError: If `leg.name` is already in use.
    """
    cursor = connection.execute(
        """
        INSERT INTO leg (name, note, created_at, discount_level)
        VALUES (?, ?, ?, ?)
        """,
        (
            leg.name,
            leg.note,
            datetime.now(timezone.utc).isoformat(),
            leg.discount_level,
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, leg: Leg) -> None:
    """Update an existing LEG's data.

    Args:
        connection: Open SQLite connection.
        leg: LEG with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `leg.id` is `None`.
        sqlite3.IntegrityError: If `leg.name` is already used by a
            different LEG.
    """
    if leg.id is None:
        raise ValueError("Cannot update a LEG without an id.")
    connection.execute(
        """
        UPDATE leg SET
            name = ?, note = ?, discount_level = ?
        WHERE id = ?
        """,
        (leg.name, leg.note, leg.discount_level, leg.id),
    )
    connection.commit()


def count_metering_points(connection: sqlite3.Connection, leg_id: int) -> int:
    """Count the metering points currently assigned to a LEG.

    Used to guard deletion: a LEG with assigned metering points must not be
    deleted (see `delete`).

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG.

    Returns:
        The number of `metering_point` rows referencing this LEG.
    """
    row = connection.execute(
        "SELECT COUNT(*) AS n FROM metering_point WHERE leg_id = ?", (leg_id,)
    ).fetchone()
    return row["n"]


class LegInUseError(Exception):
    """Raised when deleting a LEG that still has assigned metering points."""


def delete(connection: sqlite3.Connection, leg_id: int) -> None:
    """Delete a LEG, but only if no MeteringPoint is assigned to it.

    Args:
        connection: Open SQLite connection.
        leg_id: Primary key of the LEG to delete.

    Returns:
        None.

    Raises:
        LegInUseError: If one or more metering points still reference this LEG.
    """
    if count_metering_points(connection, leg_id) > 0:
        raise LegInUseError("LEG kann nicht gelöscht werden: es sind noch Messpunkte zugeordnet.")
    connection.execute("DELETE FROM leg WHERE id = ?", (leg_id,))
    connection.commit()
