"""Messpunkt (metering point): the grid operator's own measurement point,
uniquely identified by its `messpunkt_bezeichnung` (VNB id) -- never by a
postal address, which is not an identity key (an address can host several
Messpunkte, e.g. a multi-family building).
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

#: A Messpunkt measures either consumption or feed-in, never both.
MESSRICHTUNG_BEZUG = "bezug"
MESSRICHTUNG_EINSPEISUNG = "einspeisung"
ALL_MESSRICHTUNGEN = frozenset({MESSRICHTUNG_BEZUG, MESSRICHTUNG_EINSPEISUNG})


@dataclass
class Messpunkt:
    """A single grid operator metering point.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        messpunkt_bezeichnung: The grid operator's own metering point id
            (business key), as used in EBIX/SDAT-CH and CSV exports.
        messrichtung: Either `MESSRICHTUNG_BEZUG` (consumption) or
            `MESSRICHTUNG_EINSPEISUNG` (feed-in).
        standort_id: Foreign key to the `Standort` this Messpunkt is
            physically installed at.
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    messpunkt_bezeichnung: str
    messrichtung: str
    standort_id: int
    created_at: str

    @property
    def is_bezug(self) -> bool:
        """Whether this Messpunkt measures consumption.

        Returns:
            `True` if `messrichtung` is `MESSRICHTUNG_BEZUG`.
        """
        return self.messrichtung == MESSRICHTUNG_BEZUG

    @property
    def is_einspeisung(self) -> bool:
        """Whether this Messpunkt measures feed-in.

        Returns:
            `True` if `messrichtung` is `MESSRICHTUNG_EINSPEISUNG`.
        """
        return self.messrichtung == MESSRICHTUNG_EINSPEISUNG

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Messpunkt":
        """Build a `Messpunkt` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `messpunkt` table.

        Returns:
            The corresponding `Messpunkt` dataclass instance.
        """
        return Messpunkt(
            id=row["id"],
            messpunkt_bezeichnung=row["messpunkt_bezeichnung"],
            messrichtung=row["messrichtung"],
            standort_id=row["standort_id"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Messpunkt]:
    """List all Messpunkte, ordered by their designation.

    Args:
        connection: Open SQLite connection.

    Returns:
        All metering points, sorted by `messpunkt_bezeichnung`.
    """
    rows = connection.execute(
        "SELECT * FROM messpunkt ORDER BY messpunkt_bezeichnung"
    ).fetchall()
    return [Messpunkt.from_row(row) for row in rows]


def list_for_standort(connection: sqlite3.Connection, standort_id: int) -> list[Messpunkt]:
    """List all Messpunkte belonging to one Standort.

    Args:
        connection: Open SQLite connection.
        standort_id: Primary key of the site.

    Returns:
        All metering points at that site, sorted by `messpunkt_bezeichnung`.
    """
    rows = connection.execute(
        "SELECT * FROM messpunkt WHERE standort_id = ? ORDER BY messpunkt_bezeichnung",
        (standort_id,),
    ).fetchall()
    return [Messpunkt.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, messpunkt_id: int) -> Optional[Messpunkt]:
    """Fetch a single Messpunkt by id.

    Args:
        connection: Open SQLite connection.
        messpunkt_id: Primary key of the metering point.

    Returns:
        The matching `Messpunkt`, or `None` if no such id exists.
    """
    row = connection.execute(
        "SELECT * FROM messpunkt WHERE id = ?", (messpunkt_id,)
    ).fetchone()
    return Messpunkt.from_row(row) if row else None


def get_by_bezeichnung(
    connection: sqlite3.Connection, messpunkt_bezeichnung: str
) -> Optional[Messpunkt]:
    """Fetch a single Messpunkt by its business key.

    Args:
        connection: Open SQLite connection.
        messpunkt_bezeichnung: Metering point id as it appears in grid
            operator data exports.

    Returns:
        The matching `Messpunkt`, or `None` if unknown.
    """
    row = connection.execute(
        "SELECT * FROM messpunkt WHERE messpunkt_bezeichnung = ?", (messpunkt_bezeichnung,)
    ).fetchone()
    return Messpunkt.from_row(row) if row else None


def create(connection: sqlite3.Connection, messpunkt: Messpunkt) -> int:
    """Insert a new Messpunkt.

    Args:
        connection: Open SQLite connection.
        messpunkt: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created metering point.

    Raises:
        ValueError: If `messpunkt.messrichtung` is not recognized.
    """
    if messpunkt.messrichtung not in ALL_MESSRICHTUNGEN:
        raise ValueError(f"Unknown messrichtung: {messpunkt.messrichtung!r}")
    cursor = connection.execute(
        """
        INSERT INTO messpunkt (messpunkt_bezeichnung, messrichtung, standort_id, created_at)
        VALUES (?, ?, ?, ?)
        """,
        (
            messpunkt.messpunkt_bezeichnung,
            messpunkt.messrichtung,
            messpunkt.standort_id,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, messpunkt: Messpunkt) -> None:
    """Update an existing Messpunkt's data.

    Args:
        connection: Open SQLite connection.
        messpunkt: Metering point with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `messpunkt.id` is `None` or `messrichtung` is unrecognized.
    """
    if messpunkt.id is None:
        raise ValueError("Cannot update a Messpunkt without an id.")
    if messpunkt.messrichtung not in ALL_MESSRICHTUNGEN:
        raise ValueError(f"Unknown messrichtung: {messpunkt.messrichtung!r}")
    connection.execute(
        """
        UPDATE messpunkt SET
            messpunkt_bezeichnung = ?, messrichtung = ?, standort_id = ?
        WHERE id = ?
        """,
        (
            messpunkt.messpunkt_bezeichnung,
            messpunkt.messrichtung,
            messpunkt.standort_id,
            messpunkt.id,
        ),
    )
    connection.commit()


def delete(connection: sqlite3.Connection, messpunkt_id: int) -> None:
    """Delete a Messpunkt along with its Zuordnungen and readings (cascade).

    Args:
        connection: Open SQLite connection.
        messpunkt_id: Primary key of the metering point to delete.

    Returns:
        None.
    """
    connection.execute("DELETE FROM messpunkt WHERE id = ?", (messpunkt_id,))
    connection.commit()
