"""Meters (Zähler) delivering 15-minute readings from the grid operator."""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

#: Meter roles that represent consumption (Bezug) for the distribution engine.
CONSUMPTION_ROLES = frozenset({"bezug", "bezug_fix", "bezug_geschaltet"})

#: Meter roles that represent local production (Produktion).
PRODUCTION_ROLES = frozenset({"produktion"})

ALL_ROLES = CONSUMPTION_ROLES | PRODUCTION_ROLES


@dataclass
class Meter:
    """A physical meter identified by its metering point id.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        metering_point_id: The metering point id as used by the grid
            operator's EBIX/CSV exports (business key).
        label: Human-readable label, e.g. "Wärmepumpe Haus 3".
        building_address: Address of the building the meter is installed in.
        role: One of "bezug", "produktion", "bezug_fix", "bezug_geschaltet".
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    metering_point_id: str
    label: str
    building_address: str
    role: str
    created_at: str

    @property
    def is_consumption(self) -> bool:
        """Whether this meter counts towards consumption `C(t)`.

        Returns:
            `True` if the meter's role is one of the consumption roles.
        """
        return self.role in CONSUMPTION_ROLES

    @property
    def is_production(self) -> bool:
        """Whether this meter counts towards production `P(t)`.

        Returns:
            `True` if the meter's role is the production role.
        """
        return self.role in PRODUCTION_ROLES

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Meter":
        """Build a `Meter` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `meters` table.

        Returns:
            The corresponding `Meter` dataclass instance.
        """
        return Meter(
            id=row["id"],
            metering_point_id=row["metering_point_id"],
            label=row["label"],
            building_address=row["building_address"],
            role=row["role"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Meter]:
    """List all meters ordered by label.

    Args:
        connection: Open SQLite connection.

    Returns:
        All meters, alphabetically sorted by label.
    """
    rows = connection.execute("SELECT * FROM meters ORDER BY label").fetchall()
    return [Meter.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, meter_id: int) -> Optional[Meter]:
    """Fetch a single meter by id.

    Args:
        connection: Open SQLite connection.
        meter_id: Primary key of the meter.

    Returns:
        The matching `Meter`, or `None` if no such id exists.
    """
    row = connection.execute(
        "SELECT * FROM meters WHERE id = ?", (meter_id,)
    ).fetchone()
    return Meter.from_row(row) if row else None


def get_by_metering_point_id(
    connection: sqlite3.Connection, metering_point_id: str
) -> Optional[Meter]:
    """Fetch a single meter by its business key (metering point id).

    Args:
        connection: Open SQLite connection.
        metering_point_id: Metering point id as it appears in grid operator
            data exports.

    Returns:
        The matching `Meter`, or `None` if unknown.
    """
    row = connection.execute(
        "SELECT * FROM meters WHERE metering_point_id = ?", (metering_point_id,)
    ).fetchone()
    return Meter.from_row(row) if row else None


def create(connection: sqlite3.Connection, meter: Meter) -> int:
    """Insert a new meter.

    Args:
        connection: Open SQLite connection.
        meter: Meter data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created meter.

    Raises:
        ValueError: If `meter.role` is not a recognized role.
    """
    if meter.role not in ALL_ROLES:
        raise ValueError(f"Unknown meter role: {meter.role!r}")
    cursor = connection.execute(
        """
        INSERT INTO meters
            (metering_point_id, label, building_address, role, created_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            meter.metering_point_id,
            meter.label,
            meter.building_address,
            meter.role,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, meter: Meter) -> None:
    """Update an existing meter's data.

    Args:
        connection: Open SQLite connection.
        meter: Meter with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `meter.id` is `None` or `meter.role` is unrecognized.
    """
    if meter.id is None:
        raise ValueError("Cannot update a meter without an id.")
    if meter.role not in ALL_ROLES:
        raise ValueError(f"Unknown meter role: {meter.role!r}")
    connection.execute(
        """
        UPDATE meters SET
            metering_point_id = ?, label = ?, building_address = ?, role = ?
        WHERE id = ?
        """,
        (
            meter.metering_point_id,
            meter.label,
            meter.building_address,
            meter.role,
            meter.id,
        ),
    )
    connection.commit()


def delete(connection: sqlite3.Connection, meter_id: int) -> None:
    """Delete a meter along with its assignments and readings (cascade).

    Args:
        connection: Open SQLite connection.
        meter_id: Primary key of the meter to delete.

    Returns:
        None.
    """
    connection.execute("DELETE FROM meters WHERE id = ?", (meter_id,))
    connection.commit()
