"""Participants (Teilnehmer) of the local energy community."""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Participant:
    """A person or company that owns one or more meters in the LEG.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        name: Full name or company name.
        address_street: Street and house number.
        address_zip: Postal code.
        address_city: City.
        address_country: ISO-3166 alpha-2 country code.
        iban: Bank IBAN used for credit note payouts.
        email: Optional contact email address.
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    name: str
    address_street: str
    address_zip: str
    address_city: str
    address_country: str
    iban: str
    email: str
    created_at: str

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Participant":
        """Build a `Participant` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `participants` table.

        Returns:
            The corresponding `Participant` dataclass instance.
        """
        return Participant(
            id=row["id"],
            name=row["name"],
            address_street=row["address_street"],
            address_zip=row["address_zip"],
            address_city=row["address_city"],
            address_country=row["address_country"],
            iban=row["iban"],
            email=row["email"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Participant]:
    """List all participants ordered by name.

    Args:
        connection: Open SQLite connection.

    Returns:
        All participants, alphabetically sorted by name.
    """
    rows = connection.execute("SELECT * FROM participants ORDER BY name").fetchall()
    return [Participant.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, participant_id: int) -> Optional[Participant]:
    """Fetch a single participant by id.

    Args:
        connection: Open SQLite connection.
        participant_id: Primary key of the participant.

    Returns:
        The matching `Participant`, or `None` if no such id exists.
    """
    row = connection.execute(
        "SELECT * FROM participants WHERE id = ?", (participant_id,)
    ).fetchone()
    return Participant.from_row(row) if row else None


def create(connection: sqlite3.Connection, participant: Participant) -> int:
    """Insert a new participant.

    Args:
        connection: Open SQLite connection.
        participant: Participant data to insert; `id` and `created_at` are
            ignored and generated by this function.

    Returns:
        The primary key of the newly created participant.
    """
    cursor = connection.execute(
        """
        INSERT INTO participants
            (name, address_street, address_zip, address_city, address_country,
             iban, email, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            participant.name,
            participant.address_street,
            participant.address_zip,
            participant.address_city,
            participant.address_country,
            participant.iban,
            participant.email,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, participant: Participant) -> None:
    """Update an existing participant's data.

    Args:
        connection: Open SQLite connection.
        participant: Participant with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `participant.id` is `None`.
    """
    if participant.id is None:
        raise ValueError("Cannot update a participant without an id.")
    connection.execute(
        """
        UPDATE participants SET
            name = ?, address_street = ?, address_zip = ?, address_city = ?,
            address_country = ?, iban = ?, email = ?
        WHERE id = ?
        """,
        (
            participant.name,
            participant.address_street,
            participant.address_zip,
            participant.address_city,
            participant.address_country,
            participant.iban,
            participant.email,
            participant.id,
        ),
    )
    connection.commit()


def delete(connection: sqlite3.Connection, participant_id: int) -> None:
    """Delete a participant.

    Meters remain untouched; any of the participant's meter assignments are
    removed via ``ON DELETE CASCADE``.

    Args:
        connection: Open SQLite connection.
        participant_id: Primary key of the participant to delete.

    Returns:
        None.
    """
    connection.execute("DELETE FROM participants WHERE id = ?", (participant_id,))
    connection.commit()
