"""Named, reusable email signatures.

Maintained on their own page under "Kommunikation" (see
`app.gui.pages.signaturen`), independent of any single send -- a
signature is picked (or not picked at all) per send on the E-Mail-Versand
page (`app.gui.pages.email_versand`), never applied implicitly. Deleting a
signature is always safe: nothing else references a signature by id, a
past send's actually-used text is already part of its own logged body
(see `app.models.email_log`), not a live reference back here.
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Signature:
    """One named, reusable signature text block.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        name: Short label shown when choosing a signature (e.g. "Vorstand
            LEG Ittigen"). Must be unique.
        content: The signature text itself, plain text (no rich
            formatting, consistent with the rest of `app.emailing`).
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    name: str
    content: str
    created_at: str

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Signature":
        """Build a `Signature` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `signatures` table.

        Returns:
            The corresponding `Signature` dataclass instance.
        """
        return Signature(
            id=row["id"],
            name=row["name"],
            content=row["content"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Signature]:
    """List all signatures, ordered by name.

    Args:
        connection: Open SQLite connection.

    Returns:
        All signatures, sorted by `name`.
    """
    rows = connection.execute("SELECT * FROM signatures ORDER BY name").fetchall()
    return [Signature.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, signature_id: int) -> Optional[Signature]:
    """Fetch a single signature by id.

    Args:
        connection: Open SQLite connection.
        signature_id: Primary key of the signature.

    Returns:
        The matching `Signature`, or `None` if no such id exists.
    """
    row = connection.execute(
        "SELECT * FROM signatures WHERE id = ?", (signature_id,)
    ).fetchone()
    return Signature.from_row(row) if row else None


def get_by_name(connection: sqlite3.Connection, name: str) -> Optional[Signature]:
    """Fetch a single signature by its exact name.

    Args:
        connection: Open SQLite connection.
        name: Signature name to look up.

    Returns:
        The matching `Signature`, or `None` if no such name exists.
    """
    row = connection.execute(
        "SELECT * FROM signatures WHERE name = ?", (name,)
    ).fetchone()
    return Signature.from_row(row) if row else None


def create(connection: sqlite3.Connection, signature: Signature) -> int:
    """Insert a new signature.

    Args:
        connection: Open SQLite connection.
        signature: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created signature.

    Raises:
        sqlite3.IntegrityError: If `signature.name` is already in use.
    """
    cursor = connection.execute(
        """
        INSERT INTO signatures (name, content, created_at)
        VALUES (?, ?, ?)
        """,
        (
            signature.name,
            signature.content,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, signature: Signature) -> None:
    """Update an existing signature's name/content.

    Args:
        connection: Open SQLite connection.
        signature: Signature with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `signature.id` is `None`.
        sqlite3.IntegrityError: If `signature.name` is already used by a
            different signature.
    """
    if signature.id is None:
        raise ValueError("Cannot update a Signature without an id.")
    connection.execute(
        "UPDATE signatures SET name = ?, content = ? WHERE id = ?",
        (signature.name, signature.content, signature.id),
    )
    connection.commit()


def delete(connection: sqlite3.Connection, signature_id: int) -> None:
    """Delete a signature.

    Args:
        connection: Open SQLite connection.
        signature_id: Primary key of the signature to delete.

    Returns:
        None.
    """
    connection.execute("DELETE FROM signatures WHERE id = ?", (signature_id,))
    connection.commit()
