"""site (connection site): the physical grid connection point a
substation area is attached to, and that groups one or more metering points.

substation area membership is deliberately a property of the site, never of
a Person or MeteringPoint -- see the module docstring of
`app.models.substation_area`. LEG membership, by contrast, is a property of the
individual MeteringPoint (see `app.models.leg`), not of the site.
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Site:
    """One physical grid connection point (site).

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        street: Street name (without house number).
        house_number: House number.
        postal_code: Postal code.
        municipality: Municipality.
        address_detail: Optional detail (e.g. floor/unit) within that address.
        substation_area_id: Foreign key to the assigned `substation area`, `None`
            until manually assigned.
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    street: str
    house_number: str
    postal_code: str
    municipality: str
    address_detail: str
    substation_area_id: Optional[int]
    created_at: str

    @property
    def full_address(self) -> str:
        """The full postal address as a single display string.

        Returns:
            `"<address> <Hausnummer>, <PLZ> <Gemeinde>"`, with missing
            parts omitted gracefully.
        """
        street = " ".join(p for p in (self.street, self.house_number) if p)
        city = " ".join(p for p in (self.postal_code, self.municipality) if p)
        return ", ".join(p for p in (street, city) if p)

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Site":
        """Build a `site` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `site` table.

        Returns:
            The corresponding `site` dataclass instance.
        """
        return Site(
            id=row["id"],
            street=row["street"],
            house_number=row["house_number"],
            postal_code=row["postal_code"],
            municipality=row["municipality"],
            address_detail=row["address_detail"],
            substation_area_id=row["substation_area_id"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Site]:
    """List all sites, ordered by municipality, street (alphabetically),
    then house number (numerically, e.g. "2" before "10").

    Args:
        connection: Open SQLite connection.

    Returns:
        All connection sites, sorted by `municipality`, `street`, `house_number`.
    """
    rows = connection.execute(
        """
        SELECT * FROM site
        ORDER BY municipality, street, CAST(house_number AS INTEGER), house_number
        """
    ).fetchall()
    return [Site.from_row(row) for row in rows]


def find_by_address(
    connection: sqlite3.Connection, street: str, house_number: str, postal_code: str
) -> Optional[Site]:
    """Fetch a site by exact (case-insensitive) address/Hausnummer/PLZ match.

    Used to warn about likely duplicate sites -- the same physical
    address entered twice by mistake. `address_detail` is deliberately not part of
    the match: it is a descriptive detail (e.g. floor/unit) within one
    site, not a way to distinguish several sites at one address (a
    multi-family building is one site with several metering points, see
    `app.models.metering_point`).

    Args:
        connection: Open SQLite connection.
        street: Street name to match.
        house_number: House number to match.
        postal_code: Postal code to match.

    Returns:
        The matching `site`, or `None` if no such address exists.
    """
    row = connection.execute(
        """
        SELECT * FROM site
        WHERE lower(street) = lower(?) AND lower(house_number) = lower(?) AND lower(postal_code) = lower(?)
        """,
        (street, house_number, postal_code),
    ).fetchone()
    return Site.from_row(row) if row else None


def get(connection: sqlite3.Connection, site_id: int) -> Optional[Site]:
    """Fetch a single site by id.

    Args:
        connection: Open SQLite connection.
        site_id: Primary key of the site.

    Returns:
        The matching `site`, or `None` if no such id exists.
    """
    row = connection.execute(
        "SELECT * FROM site WHERE id = ?", (site_id,)
    ).fetchone()
    return Site.from_row(row) if row else None


def create(connection: sqlite3.Connection, site: Site) -> int:
    """Insert a new site.

    Args:
        connection: Open SQLite connection.
        site: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created site.
    """
    cursor = connection.execute(
        """
        INSERT INTO site
            (street, house_number, postal_code, municipality, address_detail, substation_area_id, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            site.street,
            site.house_number,
            site.postal_code,
            site.municipality,
            site.address_detail,
            site.substation_area_id,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, site: Site) -> None:
    """Update an existing site's data.

    Args:
        connection: Open SQLite connection.
        site: Site with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `site.id` is `None`.
    """
    if site.id is None:
        raise ValueError("Cannot update a Standort without an id.")
    connection.execute(
        """
        UPDATE site SET
            street = ?, house_number = ?, postal_code = ?, municipality = ?, address_detail = ?,
            substation_area_id = ?
        WHERE id = ?
        """,
        (
            site.street,
            site.house_number,
            site.postal_code,
            site.municipality,
            site.address_detail,
            site.substation_area_id,
            site.id,
        ),
    )
    connection.commit()


def delete(connection: sqlite3.Connection, site_id: int) -> None:
    """Delete a site along with its metering points (cascade).

    Args:
        connection: Open SQLite connection.
        site_id: Primary key of the site to delete.

    Returns:
        None.
    """
    connection.execute("DELETE FROM site WHERE id = ?", (site_id,))
    connection.commit()
