"""Standort (connection site): the physical grid connection point a
Trafokreis is attached to, and that groups one or more Messpunkte.

Trafokreis membership is deliberately a property of the Standort, never of
a Person or Messpunkt -- see the module docstring of
`app.models.trafokreis`. LEG membership, by contrast, is a property of the
individual Messpunkt (see `app.models.leg`), not of the Standort.
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Standort:
    """One physical grid connection point (site).

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        adresse: Street name (without house number).
        hausnummer: House number.
        plz: Postal code.
        gemeinde: Municipality.
        lage: Optional detail (e.g. floor/unit) within that address.
        trafokreis_id: Foreign key to the assigned `Trafokreis`, `None`
            until manually assigned.
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    adresse: str
    hausnummer: str
    plz: str
    gemeinde: str
    lage: str
    trafokreis_id: Optional[int]
    created_at: str

    @property
    def adresse_vollstaendig(self) -> str:
        """The full postal address as a single display string.

        Returns:
            `"<Adresse> <Hausnummer>, <PLZ> <Gemeinde>"`, with missing
            parts omitted gracefully.
        """
        strasse = " ".join(p for p in (self.adresse, self.hausnummer) if p)
        ort = " ".join(p for p in (self.plz, self.gemeinde) if p)
        return ", ".join(p for p in (strasse, ort) if p)

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Standort":
        """Build a `Standort` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `standort` table.

        Returns:
            The corresponding `Standort` dataclass instance.
        """
        return Standort(
            id=row["id"],
            adresse=row["adresse"],
            hausnummer=row["hausnummer"],
            plz=row["plz"],
            gemeinde=row["gemeinde"],
            lage=row["lage"],
            trafokreis_id=row["trafokreis_id"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Standort]:
    """List all Standorte, ordered by municipality, street (alphabetically),
    then house number (numerically, e.g. "2" before "10").

    Args:
        connection: Open SQLite connection.

    Returns:
        All connection sites, sorted by `gemeinde`, `adresse`, `hausnummer`.
    """
    rows = connection.execute(
        """
        SELECT * FROM standort
        ORDER BY gemeinde, adresse, CAST(hausnummer AS INTEGER), hausnummer
        """
    ).fetchall()
    return [Standort.from_row(row) for row in rows]


def find_by_address(
    connection: sqlite3.Connection, adresse: str, hausnummer: str, plz: str
) -> Optional[Standort]:
    """Fetch a Standort by exact (case-insensitive) Adresse/Hausnummer/PLZ match.

    Used to warn about likely duplicate Standorte -- the same physical
    address entered twice by mistake. `lage` is deliberately not part of
    the match: it is a descriptive detail (e.g. floor/unit) within one
    Standort, not a way to distinguish several Standorte at one address (a
    multi-family building is one Standort with several Messpunkte, see
    `app.models.messpunkt`).

    Args:
        connection: Open SQLite connection.
        adresse: Street name to match.
        hausnummer: House number to match.
        plz: Postal code to match.

    Returns:
        The matching `Standort`, or `None` if no such address exists.
    """
    row = connection.execute(
        """
        SELECT * FROM standort
        WHERE lower(adresse) = lower(?) AND lower(hausnummer) = lower(?) AND lower(plz) = lower(?)
        """,
        (adresse, hausnummer, plz),
    ).fetchone()
    return Standort.from_row(row) if row else None


def get(connection: sqlite3.Connection, standort_id: int) -> Optional[Standort]:
    """Fetch a single Standort by id.

    Args:
        connection: Open SQLite connection.
        standort_id: Primary key of the site.

    Returns:
        The matching `Standort`, or `None` if no such id exists.
    """
    row = connection.execute(
        "SELECT * FROM standort WHERE id = ?", (standort_id,)
    ).fetchone()
    return Standort.from_row(row) if row else None


def create(connection: sqlite3.Connection, standort: Standort) -> int:
    """Insert a new Standort.

    Args:
        connection: Open SQLite connection.
        standort: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created site.
    """
    cursor = connection.execute(
        """
        INSERT INTO standort
            (adresse, hausnummer, plz, gemeinde, lage, trafokreis_id, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            standort.adresse,
            standort.hausnummer,
            standort.plz,
            standort.gemeinde,
            standort.lage,
            standort.trafokreis_id,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, standort: Standort) -> None:
    """Update an existing Standort's data.

    Args:
        connection: Open SQLite connection.
        standort: Site with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `standort.id` is `None`.
    """
    if standort.id is None:
        raise ValueError("Cannot update a Standort without an id.")
    connection.execute(
        """
        UPDATE standort SET
            adresse = ?, hausnummer = ?, plz = ?, gemeinde = ?, lage = ?,
            trafokreis_id = ?
        WHERE id = ?
        """,
        (
            standort.adresse,
            standort.hausnummer,
            standort.plz,
            standort.gemeinde,
            standort.lage,
            standort.trafokreis_id,
            standort.id,
        ),
    )
    connection.commit()


def delete(connection: sqlite3.Connection, standort_id: int) -> None:
    """Delete a Standort along with its Messpunkte (cascade).

    Args:
        connection: Open SQLite connection.
        standort_id: Primary key of the site to delete.

    Returns:
        None.
    """
    connection.execute("DELETE FROM standort WHERE id = ?", (standort_id,))
    connection.commit()
