"""substation area (transformer circuit): the physical grid-topology grouping a
site belongs to. Purely a property of the site -- never of a
Person or MeteringPoint directly.

A substation area is distinct from a LEG (see `app.models.leg`): the substation area
is what the grid operator (BKW) actually groups sites by, while a LEG
is the administrative/billing group an individual MeteringPoint opts into. By
default a LEG matches one substation area, but two metering points on different
substation areas can deliberately share one LEG -- at a correspondingly lower
BKW discount for the cross-substation-area share, which this app never computes
but can flag (see `app.domain.leg_composition`).
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


@dataclass
class SubstationArea:
    """One physical transformer circuit.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        name: A self-chosen or pseudo name used within the app (e.g. to
            avoid using the real BKW designation in the UI). Must be
            unique.
        bkw_designation: The official BKW substation area designation/number
            (e.g. "TRA21359"), if known.
        note: Free-text notes (optional).
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    name: str
    bkw_designation: str
    note: str
    created_at: str

    @staticmethod
    def from_row(row: sqlite3.Row) -> "SubstationArea":
        """Build a `substation area` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `substation area` table.

        Returns:
            The corresponding `substation area` dataclass instance.
        """
        return SubstationArea(
            id=row["id"],
            name=row["name"],
            bkw_designation=row["bkw_designation"],
            note=row["note"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[SubstationArea]:
    """List all substation areas, ordered by name.

    Args:
        connection: Open SQLite connection.

    Returns:
        All substation areas, sorted by `name`.
    """
    rows = connection.execute("SELECT * FROM substation_area ORDER BY name").fetchall()
    return [SubstationArea.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, substation_area_id: int) -> Optional[SubstationArea]:
    """Fetch a single substation area by id.

    Args:
        connection: Open SQLite connection.
        substation_area_id: Primary key of the substation area.

    Returns:
        The matching `substation area`, or `None` if no such id exists.
    """
    row = connection.execute("SELECT * FROM substation_area WHERE id = ?", (substation_area_id,)).fetchone()
    return SubstationArea.from_row(row) if row else None


def get_by_name(connection: sqlite3.Connection, name: str) -> Optional[SubstationArea]:
    """Fetch a single substation area by its exact name.

    Args:
        connection: Open SQLite connection.
        name: substation area name to look up.

    Returns:
        The matching `substation area`, or `None` if no such name exists.
    """
    row = connection.execute("SELECT * FROM substation_area WHERE name = ?", (name,)).fetchone()
    return SubstationArea.from_row(row) if row else None


def create(connection: sqlite3.Connection, substation_area: SubstationArea) -> int:
    """Insert a new substation area.

    Args:
        connection: Open SQLite connection.
        substation area: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created substation area.

    Raises:
        sqlite3.IntegrityError: If `substation area.name` is already in use.
    """
    cursor = connection.execute(
        """
        INSERT INTO substation_area (name, bkw_designation, note, created_at)
        VALUES (?, ?, ?, ?)
        """,
        (
            substation_area.name,
            substation_area.bkw_designation,
            substation_area.note,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, substation_area: SubstationArea) -> None:
    """Update an existing substation area's data.

    Args:
        connection: Open SQLite connection.
        substation area: substation area with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `substation area.id` is `None`.
        sqlite3.IntegrityError: If `substation area.name` is already used by a
            different substation area.
    """
    if substation_area.id is None:
        raise ValueError("Cannot update a substation area without an id.")
    connection.execute(
        """
        UPDATE substation_area SET
            name = ?, bkw_designation = ?, note = ?
        WHERE id = ?
        """,
        (substation_area.name, substation_area.bkw_designation, substation_area.note, substation_area.id),
    )
    connection.commit()


def count_sites(connection: sqlite3.Connection, substation_area_id: int) -> int:
    """Count the sites currently assigned to a substation area.

    Used to guard deletion: a substation area with assigned sites must not
    be deleted (see `delete`).

    Args:
        connection: Open SQLite connection.
        substation_area_id: Primary key of the substation area.

    Returns:
        The number of `site` rows referencing this substation area.
    """
    row = connection.execute(
        "SELECT COUNT(*) AS n FROM site WHERE substation_area_id = ?", (substation_area_id,)
    ).fetchone()
    return row["n"]


class SubstationAreaInUseError(Exception):
    """Raised when deleting a substation area that still has assigned sites."""


def delete(connection: sqlite3.Connection, substation_area_id: int) -> None:
    """Delete a substation area, but only if no site is assigned to it.

    Args:
        connection: Open SQLite connection.
        substation_area_id: Primary key of the substation area to delete.

    Returns:
        None.

    Raises:
        SubstationAreaInUseError: If one or more sites still reference
            this substation area.
    """
    if count_sites(connection, substation_area_id) > 0:
        raise SubstationAreaInUseError(
            "Trafokreis kann nicht gelöscht werden: es sind noch Standorte zugeordnet."
        )
    connection.execute("DELETE FROM substation_area WHERE id = ?", (substation_area_id,))
    connection.commit()
