"""Trafokreis (transformer circuit): the physical grid-topology grouping a
Standort belongs to. Purely a property of the Standort -- never of a
Person or Messpunkt directly.

A Trafokreis is distinct from a LEG (see `app.models.leg`): the Trafokreis
is what the grid operator (BKW) actually groups Standorte by, while a LEG
is the administrative/billing group an individual Messpunkt opts into. By
default a LEG matches one Trafokreis, but two Messpunkte on different
Trafokreise can deliberately share one LEG -- at a correspondingly lower
BKW discount for the cross-Trafokreis share, which this app never computes
but can flag (see `app.domain.leg_composition`).
"""

import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


@dataclass
class Trafokreis:
    """One physical transformer circuit.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        name: A self-chosen or pseudo name used within the app (e.g. to
            avoid using the real BKW designation in the UI). Must be
            unique.
        bkw_bezeichnung: The official BKW Trafokreis designation/number
            (e.g. "TRA21359"), if known.
        bemerkung: Free-text notes (optional).
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    name: str
    bkw_bezeichnung: str
    bemerkung: str
    created_at: str

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Trafokreis":
        """Build a `Trafokreis` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `trafokreis` table.

        Returns:
            The corresponding `Trafokreis` dataclass instance.
        """
        return Trafokreis(
            id=row["id"],
            name=row["name"],
            bkw_bezeichnung=row["bkw_bezeichnung"],
            bemerkung=row["bemerkung"],
            created_at=row["created_at"],
        )


def list_all(connection: sqlite3.Connection) -> list[Trafokreis]:
    """List all Trafokreise, ordered by name.

    Args:
        connection: Open SQLite connection.

    Returns:
        All Trafokreise, sorted by `name`.
    """
    rows = connection.execute("SELECT * FROM trafokreis ORDER BY name").fetchall()
    return [Trafokreis.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, trafokreis_id: int) -> Optional[Trafokreis]:
    """Fetch a single Trafokreis by id.

    Args:
        connection: Open SQLite connection.
        trafokreis_id: Primary key of the Trafokreis.

    Returns:
        The matching `Trafokreis`, or `None` if no such id exists.
    """
    row = connection.execute(
        "SELECT * FROM trafokreis WHERE id = ?", (trafokreis_id,)
    ).fetchone()
    return Trafokreis.from_row(row) if row else None


def get_by_name(connection: sqlite3.Connection, name: str) -> Optional[Trafokreis]:
    """Fetch a single Trafokreis by its exact name.

    Args:
        connection: Open SQLite connection.
        name: Trafokreis name to look up.

    Returns:
        The matching `Trafokreis`, or `None` if no such name exists.
    """
    row = connection.execute(
        "SELECT * FROM trafokreis WHERE name = ?", (name,)
    ).fetchone()
    return Trafokreis.from_row(row) if row else None


def create(connection: sqlite3.Connection, trafokreis: Trafokreis) -> int:
    """Insert a new Trafokreis.

    Args:
        connection: Open SQLite connection.
        trafokreis: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created Trafokreis.

    Raises:
        sqlite3.IntegrityError: If `trafokreis.name` is already in use.
    """
    cursor = connection.execute(
        """
        INSERT INTO trafokreis (name, bkw_bezeichnung, bemerkung, created_at)
        VALUES (?, ?, ?, ?)
        """,
        (
            trafokreis.name,
            trafokreis.bkw_bezeichnung,
            trafokreis.bemerkung,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, trafokreis: Trafokreis) -> None:
    """Update an existing Trafokreis's data.

    Args:
        connection: Open SQLite connection.
        trafokreis: Trafokreis with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `trafokreis.id` is `None`.
        sqlite3.IntegrityError: If `trafokreis.name` is already used by a
            different Trafokreis.
    """
    if trafokreis.id is None:
        raise ValueError("Cannot update a Trafokreis without an id.")
    connection.execute(
        """
        UPDATE trafokreis SET
            name = ?, bkw_bezeichnung = ?, bemerkung = ?
        WHERE id = ?
        """,
        (trafokreis.name, trafokreis.bkw_bezeichnung, trafokreis.bemerkung, trafokreis.id),
    )
    connection.commit()


def count_standorte(connection: sqlite3.Connection, trafokreis_id: int) -> int:
    """Count the Standorte currently assigned to a Trafokreis.

    Used to guard deletion: a Trafokreis with assigned Standorte must not
    be deleted (see `delete`).

    Args:
        connection: Open SQLite connection.
        trafokreis_id: Primary key of the Trafokreis.

    Returns:
        The number of `standort` rows referencing this Trafokreis.
    """
    row = connection.execute(
        "SELECT COUNT(*) AS n FROM standort WHERE trafokreis_id = ?", (trafokreis_id,)
    ).fetchone()
    return row["n"]


class TrafokreisInUseError(Exception):
    """Raised when deleting a Trafokreis that still has assigned Standorte."""


def delete(connection: sqlite3.Connection, trafokreis_id: int) -> None:
    """Delete a Trafokreis, but only if no Standort is assigned to it.

    Args:
        connection: Open SQLite connection.
        trafokreis_id: Primary key of the Trafokreis to delete.

    Returns:
        None.

    Raises:
        TrafokreisInUseError: If one or more Standorte still reference
            this Trafokreis.
    """
    if count_standorte(connection, trafokreis_id) > 0:
        raise TrafokreisInUseError(
            "Trafokreis kann nicht gelöscht werden: es sind noch Standorte zugeordnet."
        )
    connection.execute("DELETE FROM trafokreis WHERE id = ?", (trafokreis_id,))
    connection.commit()
