"""Time-bounded assignments of Messpunkte to Personen (Zuordnungs-Historie).

A Messpunkt is physically fixed to a Standort, but the person billed for
it can change over time (e.g. a tenant moving out mid-quarter). Each row
in `zuordnung` represents one such period; `gueltig_bis = NULL` means
"still valid / open-ended". Moving never changes the Messpunkt, its
Standort, or that Standort's LEG -- only which Person the
Zuordnung points at.
"""

import sqlite3
from dataclasses import dataclass
from datetime import date, datetime, timezone
from typing import Optional


@dataclass
class Zuordnung:
    """One period during which a Messpunkt was billed to a given Person.

    Attributes:
        id: Primary key, `None` for a not-yet-persisted instance.
        person_id: Foreign key to the person.
        messpunkt_id: Foreign key to the assigned metering point.
        gueltig_von: First calendar day (inclusive) this assignment applies.
        gueltig_bis: Last calendar day (inclusive) this assignment applies,
            or `None` if the assignment is open-ended (still current).
        created_at: ISO-8601 creation timestamp.
    """

    id: Optional[int]
    person_id: int
    messpunkt_id: int
    gueltig_von: date
    gueltig_bis: Optional[date]
    created_at: str

    @staticmethod
    def from_row(row: sqlite3.Row) -> "Zuordnung":
        """Build a `Zuordnung` from a `sqlite3.Row`.

        Args:
            row: Row selected from the `zuordnung` table.

        Returns:
            The corresponding `Zuordnung` dataclass instance.
        """
        return Zuordnung(
            id=row["id"],
            person_id=row["person_id"],
            messpunkt_id=row["messpunkt_id"],
            gueltig_von=date.fromisoformat(row["gueltig_von"]),
            gueltig_bis=date.fromisoformat(row["gueltig_bis"]) if row["gueltig_bis"] else None,
            created_at=row["created_at"],
        )

    def covers(self, moment: datetime) -> bool:
        """Check whether this Zuordnung is active at a given point in time.

        Args:
            moment: Timestamp to test (only its calendar date is compared).

        Returns:
            `True` if `gueltig_von <= moment.date() <= gueltig_bis` (or
            `gueltig_bis` is `None`, meaning open-ended).
        """
        moment_date = moment.date()
        if moment_date < self.gueltig_von:
            return False
        if self.gueltig_bis is not None and moment_date > self.gueltig_bis:
            return False
        return True


def list_for_messpunkt(
    connection: sqlite3.Connection, messpunkt_id: int
) -> list[Zuordnung]:
    """List all Zuordnungen of a Messpunkt, most recent `gueltig_von` first.

    Args:
        connection: Open SQLite connection.
        messpunkt_id: Primary key of the metering point.

    Returns:
        All assignments for the metering point, ordered by `gueltig_von`
        descending.
    """
    rows = connection.execute(
        "SELECT * FROM zuordnung WHERE messpunkt_id = ? ORDER BY gueltig_von DESC",
        (messpunkt_id,),
    ).fetchall()
    return [Zuordnung.from_row(row) for row in rows]


def list_for_person(connection: sqlite3.Connection, person_id: int) -> list[Zuordnung]:
    """List all Zuordnungen of a Person, most recent `gueltig_von` first.

    Args:
        connection: Open SQLite connection.
        person_id: Primary key of the person.

    Returns:
        All assignments for the person, ordered by `gueltig_von` descending.
    """
    rows = connection.execute(
        "SELECT * FROM zuordnung WHERE person_id = ? ORDER BY gueltig_von DESC",
        (person_id,),
    ).fetchall()
    return [Zuordnung.from_row(row) for row in rows]


def get(connection: sqlite3.Connection, zuordnung_id: int) -> Optional[Zuordnung]:
    """Fetch a single Zuordnung by id.

    Args:
        connection: Open SQLite connection.
        zuordnung_id: Primary key of the assignment.

    Returns:
        The matching `Zuordnung`, or `None` if no such id exists.
    """
    row = connection.execute(
        "SELECT * FROM zuordnung WHERE id = ?", (zuordnung_id,)
    ).fetchone()
    return Zuordnung.from_row(row) if row else None


def list_all(connection: sqlite3.Connection) -> list[Zuordnung]:
    """List every Zuordnung in the database.

    Args:
        connection: Open SQLite connection.

    Returns:
        All assignments, ordered by Messpunkt id and `gueltig_von`.
    """
    rows = connection.execute(
        "SELECT * FROM zuordnung ORDER BY messpunkt_id, gueltig_von"
    ).fetchall()
    return [Zuordnung.from_row(row) for row in rows]


def create(connection: sqlite3.Connection, zuordnung: Zuordnung) -> int:
    """Insert a new Zuordnung.

    Args:
        connection: Open SQLite connection.
        zuordnung: Data to insert; `id` and `created_at` are ignored and
            generated by this function.

    Returns:
        The primary key of the newly created assignment.
    """
    cursor = connection.execute(
        """
        INSERT INTO zuordnung (person_id, messpunkt_id, gueltig_von, gueltig_bis, created_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            zuordnung.person_id,
            zuordnung.messpunkt_id,
            zuordnung.gueltig_von.isoformat(),
            zuordnung.gueltig_bis.isoformat() if zuordnung.gueltig_bis else None,
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    connection.commit()
    return cursor.lastrowid


def update(connection: sqlite3.Connection, zuordnung: Zuordnung) -> None:
    """Update an existing Zuordnung's validity period or person.

    Args:
        connection: Open SQLite connection.
        zuordnung: Assignment with `id` set to an existing record.

    Returns:
        None.

    Raises:
        ValueError: If `zuordnung.id` is `None`.
    """
    if zuordnung.id is None:
        raise ValueError("Cannot update a Zuordnung without an id.")
    connection.execute(
        """
        UPDATE zuordnung SET
            person_id = ?, messpunkt_id = ?, gueltig_von = ?, gueltig_bis = ?
        WHERE id = ?
        """,
        (
            zuordnung.person_id,
            zuordnung.messpunkt_id,
            zuordnung.gueltig_von.isoformat(),
            zuordnung.gueltig_bis.isoformat() if zuordnung.gueltig_bis else None,
            zuordnung.id,
        ),
    )
    connection.commit()


def delete(connection: sqlite3.Connection, zuordnung_id: int) -> None:
    """Delete a Zuordnung.

    Args:
        connection: Open SQLite connection.
        zuordnung_id: Primary key of the assignment to delete.

    Returns:
        None.
    """
    connection.execute("DELETE FROM zuordnung WHERE id = ?", (zuordnung_id,))
    connection.commit()


@dataclass
class ZuordnungWarning:
    """A detected problem in a Messpunkt's assignment history.

    Attributes:
        messpunkt_id: Metering point the warning refers to.
        kind: Either "overlap" (two assignments cover the same day) or
            "gap" (a day between assignments belongs to nobody).
        message: Human-readable (German) description for display in the UI.
    """

    messpunkt_id: int
    kind: str
    message: str


def find_warnings(
    connection: sqlite3.Connection, messpunkt_id: int
) -> list[ZuordnungWarning]:
    """Detect overlapping or gapped assignment periods for one Messpunkt.

    Assignments are checked pairwise after sorting by `gueltig_von`: any
    two consecutive periods that overlap, or that leave a day uncovered
    between them, produce a warning. Open-ended assignments
    (`gueltig_bis is None`) are only allowed to be the last one; an
    earlier open-ended assignment is reported as an overlap with
    everything that follows it.

    Args:
        connection: Open SQLite connection.
        messpunkt_id: Primary key of the metering point to check.

    Returns:
        A list of `ZuordnungWarning`, empty if the history is consistent.
    """
    assignments = sorted(
        list_for_messpunkt(connection, messpunkt_id), key=lambda a: a.gueltig_von
    )
    warnings: list[ZuordnungWarning] = []

    for earlier, later in zip(assignments, assignments[1:]):
        earlier_end = earlier.gueltig_bis
        if earlier_end is None or earlier_end >= later.gueltig_von:
            warnings.append(
                ZuordnungWarning(
                    messpunkt_id=messpunkt_id,
                    kind="overlap",
                    message=(
                        f"Überlappende Zuordnungen bei Messpunkt {messpunkt_id}: "
                        f"{earlier.gueltig_von} - "
                        f"{earlier_end or 'offen'} und ab {later.gueltig_von}."
                    ),
                )
            )
        else:
            from datetime import timedelta

            if earlier_end + timedelta(days=1) < later.gueltig_von:
                warnings.append(
                    ZuordnungWarning(
                        messpunkt_id=messpunkt_id,
                        kind="gap",
                        message=(
                            f"Lücke in Zuordnungen bei Messpunkt {messpunkt_id}: "
                            f"{earlier_end + timedelta(days=1)} bis "
                            f"{later.gueltig_von - timedelta(days=1)} ist "
                            "niemandem zugeordnet."
                        ),
                    )
                )

    return warnings
